### ISSUE TITLE
Underline Not Printing

### ISSUE THREAD

**Issue by atown45** [ralfstuckert/pdfbox-layout#21]
I'm using the underline annotation and it looks great when viewing the PDF document in Adobe Reader.  The problem I'm having is that when I print the PDF document the  underlines are not printed.  Is there something special I need to do to make the underlines print?

**Comment by ralfstuckert** [comment]
Yep, you are right. As a matter of fact, all annotations on PDF are not printed by standard tools like Acrobat Reader. To be quite honest, I have no idea how to deal with that. I chose the annotation since it is the proposed way how to implement underline. But like you, I'm not happy with that printint topic. Any ideas from your side?

In the meantime you could implement your own strategy  as a workaround by using the custom annotations and really draw a line. But this is not a generic solution, since some parameters depend on the used font: line thickness and distance from baseline. Alas, these values are not available in a public API :-\

**Comment by atown45** [comment]
Is there a way to turn on/off the right, left, top and bottom borders on a Frame?  A Frame prints and if I could turn off the right, left and top borders I could make it look like the text was underlined.

**Comment by ralfstuckert** [comment]
Sorry, even if you could, frames are thought as a container, so they will not obey line wrapping.

**Comment by ralfstuckert** [comment]
Fixed in 1.0.0
